backend:
  name: github
  repo: fl-nck/JAMSite

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "page"
    label: "Page"
    folder: "content/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
